In [13]:
api_key = "62b16b99957e4c2cb1f4a386a243e17e"

In [17]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'5000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': api_key,
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  data = data["data"][0:99]
  print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

[{'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'num_market_pairs': 12492, 'date_added': '2010-07-13T00:00:00.000Z', 'tags': ['mineable', 'pow', 'sha-256', 'store-of-value', 'state-channel', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'galaxy-digital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'bitcoin-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing'], 'max_supply': 21000000, 'circulating_supply': 19957806, 'total_supply': 19957806, 'infinite_supply': False, 'minted_market_cap': 1788060987240.64, 'platform': None, 'cmc_rank': 1, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 89592.06173467376, 'volume_24h': 62961894414.39702, 'volume_change_24h': -7.488, 'percent_change_1h': 0.53255739, 'percent_change_24h': -2.71178322, 'percent_change_7d': -1.58502729, 'percent_change_30d': -14.28743581, 'percent_change_60d': -28.5568527, 'percent_change_90d': -18.61378987, 'market_cap': 1788060987240.6423, 'market_cap_dominance': 58.7621, 'fully_diluted_market_cap': 1881433296428.15, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'num_market_pairs': 11232, 'date_added': '2015-08-07T00:00:00.000Z', 'tags': ['pos', 'smart-contracts', 'ethereum-ecosystem', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'hashkey-capital-portfolio', 'kenetic-capital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'sora-ecosystem', 'rsk-rbtc-ecosystem', 'world-liberty-financial-portfolio', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'sophon-ecosystem'], 'max_supply': None, 'circulating_supply': 120695422.32472062, 'total_supply': 120695422.32472062, 'infinite_supply': True, 'minted_market_cap': 366670014379.91, 'platform': None, 'cmc_rank': 2, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 3037.9778065933033, 'volume_24h': 28002353384.6621, 'volume_change_24h': -7.5563, 'percent_change_1h': 0.97849721, 'percent_change_24h': -2.59206445, 'percent_change_7d': -0.1870296, 'percent_change_30d': -12.68088186, 'percent_change_60d': -35.61621177, 'percent_change_90d': -28.72189598, 'market_cap': 366670014379.90717, 'market_cap_dominance': 12.0501, 'fully_diluted_market_cap': 366670014379.91, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 825, 'name': 'Tether USDt', 'symbol': 'USDT', 'slug': 'tether', 'num_market_pairs': 160834, 'date_added': '2015-02-25T00:00:00.000Z', 'tags': ['stablecoin', 'asset-backed-stablecoin', 'usd-stablecoin', 'fiat-stablecoin', 'tron20-ecosystem', 'rsk-rbtc-ecosystem', 'venom-ecosystem', 'world-liberty-financial-portfolio', 'binance-ecosystem', 'binance-listing', 'peaq-ecosystem', 'apertum-ecosystem', 'etherlink-ecosystem', 'duckchain-ecosystem', 'onus-ecosystem', 'sophon-ecosystem', 'zedxion-smart-chain-ecosystem', 'xlayer-ecosystem'], 'max_supply': None, 'circulating_supply': 185516177143.1422, 'total_supply': 187859713296.51648, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'}, 'infinite_supply': True, 'minted_market_cap': 187909460904.85, 'cmc_rank': 3, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:11:00.000Z', 'quote': {'USD': {'price': 1.0002648125426057, 'volume_24h': 98190521304.3945, 'volume_change_24h': -7.2585, 'percent_change_1h': 0.01352514, 'percent_change_24h': 0.00268161, 'percent_change_7d': 0.00806077, 'percent_change_30d': 0.02236641, 'percent_change_60d': -0.02429623, 'percent_change_90d': 0.02124915, 'market_cap': 185565304153.70596, 'market_cap_dominance': 6.0896, 'fully_diluted_market_cap': 187909460904.85, 'tvl': None, 'last_updated': '2025-12-05T20:11:00.000Z'}}}, {'id': 52, 'name': 'XRP', 'symbol': 'XRP', 'slug': 'xrp', 'num_market_pairs': 1764, 'date_added': '2013-08-04T00:00:00.000Z', 'tags': ['medium-of-exchange', 'enterprise-solutions', 'xrp-ecosystem', 'arrington-xrp-capital-portfolio', 'galaxy-digital-portfolio', 'a16z-portfolio', 'pantera-capital-portfolio', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'klaytn-ecosystem', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'iso-20022'], 'max_supply': 100000000000, 'circulating_supply': 60331635327, 'total_supply': 99985752852, 'infinite_supply': False, 'minted_market_cap': 203207339160.47, 'platform': None, 'cmc_rank': 4, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 2.032362945361418, 'volume_24h': 3385290836.6601343, 'volume_change_24h': -4.3522, 'percent_change_1h': 0.48863354, 'percent_change_24h': -3.02383692, 'percent_change_7d': -6.78722721, 'percent_change_30d': -13.13050976, 'percent_change_60d': -32.91806863, 'percent_change_90d': -27.35345508, 'market_cap': 122615780071.6527, 'market_cap_dominance': 4.0296, 'fully_diluted_market_cap': 203236294536.14, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 1839, 'name': 'BNB', 'symbol': 'BNB', 'slug': 'bnb', 'num_market_pairs': 2996, 'date_added': '2017-07-25T00:00:00.000Z', 'tags': ['marketplace', 'centralized-exchange', 'payments', 'smart-contracts', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'bnb-chain-ecosystem', 'layer-1', 'alleged-sec-securities', 'celsius-bankruptcy-estate', 'binance-ecosystem', 'binance-listing', 'etherlink-ecosystem', 'made-in-china'], 'max_supply': 137736017.76, 'circulating_supply': 137736017.76, 'total_supply': 137736017.76, 'infinite_supply': False, 'minted_market_cap': 121478000691.86, 'platform': None, 'cmc_rank': 5, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 881.962486410247, 'volume_24h': 1992337843.5000823, 'volume_change_24h': -8.1091, 'percent_change_1h': 0.44320932, 'percent_change_24h': -1.81829488, 'percent_change_7d': -0.34337891, 'percent_change_30d': -8.34015322, 'percent_change_60d': -27.89463881, 'percent_change_90d': 2.86230119, 'market_cap': 121478000691.85553, 'market_cap_dominance': 3.9922, 'fully_diluted_market_cap': 121478000691.86, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 3408, 'name': 'USDC', 'symbol': 'USDC', 'slug': 'usd-coin', 'num_market_pairs': 35161, 'date_added': '2018-10-08T00:00:00.000Z', 'tags': ['medium-of-exchange', 'stablecoin', 'asset-backed-stablecoin', 'stellar-ecosystem', 'coinbase-ventures-portfolio', 'usd-stablecoin', 'xdc-ecosystem', 'fiat-stablecoin', 'tron20-ecosystem', 'venom-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio', 'sonic-ecosystem', 'binance-ecosystem', 'binance-listing', 'hyperevm-ecosystem', 'etherlink-ecosystem', 'unichain-ecosystem', 'vector-smart-chain-ecosystem', 'sophon-ecosystem', 'monad-ecosystem', 'xlayer-ecosystem'], 'max_supply': None, 'circulating_supply': 78174845248.8272, 'total_supply': 78174845248.8272, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'}, 'infinite_supply': False, 'minted_market_cap': 78168625147.64, 'cmc_rank': 6, 'self_reported_circulating_supply': 60901219650.23, 'self_reported_market_cap': 60896373951.49858, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:13:00.000Z', 'quote': {'USD': {'price': 0.999920433469818, 'volume_24h': 12795489790.744015, 'volume_change_24h': -1.6523, 'percent_change_1h': 0.00356603, 'percent_change_24h': -0.00703581, 'percent_change_7d': -0.00100031, 'percent_change_30d': -0.0028332, 'percent_change_60d': 0.03009144, 'percent_change_90d': 0.00152378, 'market_cap': 78168625147.64323, 'market_cap_dominance': 2.5689, 'fully_diluted_market_cap': 78168625147.64, 'tvl': None, 'last_updated': '2025-12-05T20:13:00.000Z'}}}, {'id': 5426, 'name': 'Solana', 'symbol': 'SOL', 'slug': 'solana', 'num_market_pairs': 1057, 'date_added': '2020-04-10T00:00:00.000Z', 'tags': ['pos', 'platform', 'solana-ecosystem', 'cms-holdings-portfolio', 'kenetic-capital-portfolio', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'okx-ventures-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'alleged-sec-securities', 'cmc-crypto-awards-2024', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing'], 'max_supply': None, 'circulating_supply': 559895987.923674, 'total_supply': 615485434.3657302, 'infinite_supply': True, 'minted_market_cap': 81415030566.81, 'platform': None, 'cmc_rank': 7, 'self_reported_circulating_supply': 525236893.3, 'self_reported_market_cap': 69477156298.42847, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:11:00.000Z', 'quote': {'USD': {'price': 132.27775349502178, 'volume_24h': 4644632062.335493, 'volume_change_24h': -5.8124, 'percent_change_1h': 0.71699824, 'percent_change_24h': -5.29231437, 'percent_change_7d': -3.60567139, 'percent_change_30d': -18.88230787, 'percent_change_60d': -43.93259288, 'percent_change_90d': -33.85208055, 'market_cap': 74061783473.41945, 'market_cap_dominance': 2.4305, 'fully_diluted_market_cap': 81415030566.81, 'tvl': None, 'last_updated': '2025-12-05T20:11:00.000Z'}}}, {'id': 1958, 'name': 'TRON', 'symbol': 'TRX', 'slug': 'tron', 'num_market_pairs': 1264, 'date_added': '2017-09-13T00:00:00.000Z', 'tags': ['media', 'payments', 'tron-ecosystem', 'layer-1', 'dwf-labs-portfolio', 'alleged-sec-securities', '2017-2018-alt-season', 'tron20-ecosystem', 'world-liberty-financial-portfolio', 'binance-ecosystem', 'binance-listing', 'made-in-china'], 'max_supply': None, 'circulating_supply': 94678692320.469, 'total_supply': 94678691125.25058, 'infinite_supply': True, 'minted_market_cap': 27111157289.71, 'platform': None, 'cmc_rank': 8, 'self_reported_circulating_supply': 94667886298.43, 'self_reported_market_cap': 27108063337.353104, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 0.28634909257293384, 'volume_24h': 753227998.1488487, 'volume_change_24h': 33.3072, 'percent_change_1h': 0.16544585, 'percent_change_24h': 0.93223802, 'percent_change_7d': 1.70395639, 'percent_change_30d': -1.19576866, 'percent_change_60d': -17.32714173, 'percent_change_90d': -12.21685785, 'market_cap': 27111157631.958298, 'market_cap_dominance': 0.891, 'fully_diluted_market_cap': 27111157289.71, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 74, 'name': 'Dogecoin', 'symbol': 'DOGE', 'slug': 'dogecoin', 'num_market_pairs': 1354, 'date_added': '2013-12-15T00:00:00.000Z', 'tags': ['mineable', 'pow', 'scrypt', 'medium-of-exchange', 'memes', 'payments', 'doggone-doggerel', 'osmosis-ecosystem', 'ftx-bankruptcy-estate', 'animal-memes', 'made-in-america', 'binance-ecosystem', 'binance-listing'], 'max_supply': None, 'circulating_supply': 161579172798.57907, 'total_supply': 161579172798.57907, 'infinite_supply': True, 'minted_market_cap': 22403444396.87, 'platform': None, 'cmc_rank': 9, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 0.13865304549367136, 'volume_24h': 1266049884.9268062, 'volume_change_24h': -6.3019, 'percent_change_1h': 0.4116928, 'percent_change_24h': -6.3310947, 'percent_change_7d': -7.84828091, 'percent_change_30d': -17.34552101, 'percent_change_60d': -48.45337628, 'percent_change_90d': -34.98700187, 'market_cap': 22403444396.87117, 'market_cap_dominance': 0.7363, 'fully_diluted_market_cap': 22403444396.87, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 2010, 'name': 'Cardano', 'symbol': 'ADA', 'slug': 'cardano', 'num_market_pairs': 1629, 'date_added': '2017-10-01T00:00:00.000Z', 'tags': ['dpos', 'pos', 'platform', 'research', 'smart-contracts', 'staking', 'cardano-ecosystem', 'cardano', 'layer-1', 'alleged-sec-securities', '2017-2018-alt-season', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'iso-20022'], 'max_supply': 45000000000, 'circulating_supply': 35898690325.61103, 'total_supply': 44994874414.9962, 'infinite_supply': False, 'minted_market_cap': 18706039054.21, 'platform': None, 'cmc_rank': 10, 'self_reported_circulating_supply': 37997904336, 'self_reported_market_cap': 15797138934.791254, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:07:00.000Z', 'quote': {'USD': {'price': 0.4157371100022671, 'volume_24h': 602511518.4874531, 'volume_change_24h': -14.5196, 'percent_change_1h': 1.18871879, 'percent_change_24h': -5.80305033, 'percent_change_7d': -0.97523596, 'percent_change_30d': -23.5827272, 'percent_change_60d': -52.66159805, 'percent_change_90d': -49.09130799, 'market_cap': 14924417768.835875, 'market_cap_dominance': 0.4894, 'fully_diluted_market_cap': 18708169950.1, 'tvl': None, 'last_updated': '2025-12-05T20:07:00.000Z'}}}, {'id': 1831, 'name': 'Bitcoin Cash', 'symbol': 'BCH', 'slug': 'bitcoin-cash', 'num_market_pairs': 1101, 'date_added': '2017-07-23T00:00:00.000Z', 'tags': ['mineable', 'pow', 'sha-256', 'marketplace', 'medium-of-exchange', 'store-of-value', 'enterprise-solutions', 'payments', 'layer-1', '2017-2018-alt-season', 'made-in-america', 'binance-ecosystem', 'binance-listing'], 'max_supply': 21000000, 'circulating_supply': 19962771.875, 'total_supply': 19962771.875, 'infinite_supply': False, 'minted_market_cap': 11340885594.71, 'platform': None, 'cmc_rank': 11, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 568.1017478796672, 'volume_24h': 367754316.2291208, 'volume_change_24h': -23.0128, 'percent_change_1h': 0.13641948, 'percent_change_24h': -1.10641759, 'percent_change_7d': 3.02290499, 'percent_change_30d': 15.64382238, 'percent_change_60d': -5.88436845, 'percent_change_90d': -4.40602456, 'market_cap': 11340885594.710562, 'market_cap_dominance': 0.3727, 'fully_diluted_market_cap': 11930136705.47, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 32196, 'name': 'Hyperliquid', 'symbol': 'HYPE', 'slug': 'hyperliquid', 'num_market_pairs': 208, 'date_added': '2024-07-15T10:14:50.000Z', 'tags': ['decentralized-exchange-dex-token', 'defi', 'derivatives', 'layer-1', 'hyperliquid-ecosystem', 'binance-ecosystem', 'binance-listing', 'perp-dex-coins'], 'max_supply': 999533278, 'circulating_supply': 336685219, 'total_supply': 999533278, 'platform': {'id': 32196, 'name': 'Hyperliquid', 'symbol': 'HYPE', 'slug': 'hyperliquid', 'token_address': '0x0d01dc56dcaaca66ad901c959b4011ec'}, 'infinite_supply': False, 'minted_market_cap': 31058896115.84, 'cmc_rank': 12, 'self_reported_circulating_supply': 333931719, 'self_reported_market_cap': 10376393461.314402, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 31.073398754654995, 'volume_24h': 313166399.3629435, 'volume_change_24h': -4.9095, 'percent_change_1h': 0.9516255, 'percent_change_24h': -7.09882937, 'percent_change_7d': -9.81465509, 'percent_change_30d': -25.04503998, 'percent_change_60d': -37.20825954, 'percent_change_90d': -31.93460776, 'market_cap': 10461954064.785345, 'market_cap_dominance': 0.3438, 'fully_diluted_market_cap': 31058896115.84, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 1975, 'name': 'Chainlink', 'symbol': 'LINK', 'slug': 'chainlink', 'num_market_pairs': 2156, 'date_added': '2017-09-20T00:00:00.000Z', 'tags': ['platform', 'cosmos-ecosystem', 'defi', 'interoperability', 'iot', 'oracles', 'smart-contracts', 'ethereum-ecosystem', 'tron-ecosystem', 'polkadot', 'tokenized-stock', 'polkadot-ecosystem', 'heco-ecosystem', 'avalanche-ecosystem', 'solana-ecosystem', 'framework-ventures-portfolio', 'hedera-hashgraph-ecosystem', 'polygon-ecosystem', 'fantom-ecosystem', 'cardano-ecosystem', 'terra-ecosystem', 'web3', 'near-protocol-ecosystem', 'arbitrum-ecosystem', 'celo-ecosystem', 'defi-2', 'cross-chain', 'cronos-ecosystem', 'cardano', 'injective-ecosystem', 'bnb-chain-ecosystem', 'oasis-ecosystem', 'moonbeam-ecosystem', 'xdc-ecosystem', 'metisdao-ecosystem', 'velas-ecosystem', 'doge-chain-ecosystem', 'aptos-ecosystem', 'sui-ecosystem', 'optimism-ecosystem', 'bitcoin-ecosystem', 'real-world-assets-protocols', 'zksync-era-ecosystem', 'kadena-ecosystem', 'base-ecosystem', 'linea-ecosystem', 'sei-ecosystem', 'toncoin-ecosystem', 'paal-ecosystem', 'blast-ecosystem', 'atomicals-ecosystem', 'move-vm', 'eigenlayer-ecosystem', 'hyperliquid-ecosystem', 'gnosis-chain-ecosystem', 'ronin-ecosystem', 'astar-ecosystem', 'core-ecosystem', 'starknet-ecosystem', 'mantle-ecosystem', 'opbnb-ecosystem', 'scroll-ecosystem', 'merlin-ecosystem', 'x-layer-ecosystem', 'b²-network-ecosystem', 'mode-ecosystem', 'world-chain-mainnet-ecosystem', 'apechain-ecosystem', 'made-in-america', 'btcfi', 'world-liberty-financial-portfolio', 'corn-ecosystem', 'bonk-fun-ecosystem', 'sonic-ecosystem', 'binance-ecosystem', 'binance-listing', 'bittensor-ecosystem', 'tokenized-assets', 'xstocks-ecosystem', 'hyperevm-ecosystem', 'etherlink-ecosystem', 'bera-chain-ecosystem', 'abstract-chain-ecosystem', 'unichain-ecosystem', 'soneium-ecosystem', 'fraxtal-ecosystem', 'monad-ecosystem', 'hashkey-chain-ecosystem', 'wlfi-ecosystem', 'plasma-ecosystem', 'x402-ecosystem', 'iso-20022'], 'max_supply': 1000000000, 'circulating_supply': 696849970.4525867, 'total_supply': 1000000000, 'platform': {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'token_address': '0x514910771af9ca656af840dff83e8264ecf986ca'}, 'infinite_supply': False, 'minted_market_cap': 13558386151.7, 'cmc_rank': 13, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'tvl_ratio': None, 'last_updated': '2025-12-05T20:14:00.000Z', 'quote': {'USD': {'price': 13.558386151701958, 'volume_24h': 667182636.1003757, 'volume_change_24h': -17.5303, 'percent_change_1h': 0.88880212, 'percent_change_24h': -4.74397201, 'percent_change_7d': 2.95926829, 'percent_change_30d': -11.52221861, 'percent_change_60d': -42.37424141, 'percent_change_90d': -38.17328392, 'market_cap': 9448160989.198269, 'market_cap_dominance': 0.3103, 'fully_diluted_market_cap': 13558386151.7, 'tvl': None, 'last_updated': '2025-12-05T20:14:00.000Z'}}}, {'id': 3957, 'name': 'UNUS SED LEO', 'symbol': 'LEO', 'slug': 'unus-sed-leo', 'num_market_pairs': 64, 'date_added': '2019-05-21T00:00:00.000Z', 'tags': ['marketplace', 'centralized-exchange', 'discount-token', 'payments', 'ethereum-ecosystem', 'kenetic-capital-portfolio', 'alameda-rese

In [18]:
import pandas as pd

df = pd.json_normalize(data, sep = "_")
df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,...,quote_USD_market_cap,quote_USD_market_cap_dominance,quote_USD_fully_diluted_market_cap,quote_USD_tvl,quote_USD_last_updated,platform_id,platform_name,platform_symbol,platform_slug,platform_token_address
0,1,Bitcoin,BTC,bitcoin,12492,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.995781e+07,1.995781e+07,...,1.788061e+12,58.7621,1.881433e+12,NaN,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,11232,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.206954e+08,1.206954e+08,...,3.666700e+11,12.0501,3.666700e+11,NaN,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,160834,2015-02-25T00:00:00.000Z,"[stablecoin, asset-backed-stablecoin, usd-stab...",NaN,1.855162e+11,1.878597e+11,...,1.855653e+11,6.0896,1.879095e+11,NaN,2025-12-05T20:11:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,52,XRP,XRP,xrp,1764,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, xrp...",1.000000e+11,6.033164e+10,9.998575e+10,...,1.226158e+11,4.0296,2.032363e+11,NaN,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
4,1839,BNB,BNB,bnb,2996,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",1.377360e+08,1.377360e+08,1.377360e+08,...,1.214780e+11,3.9922,1.214780e+11,NaN,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,32880,Kaia,KAIA,kaia,168,2024-10-29T05:17:50.000Z,"[platform, enterprise-solutions, layer-1, klay...",NaN,6.185546e+09,6.185546e+09,...,4.823800e+08,0.0159,4.823800e+08,NaN,2025-12-05T20:14:00.000Z,32880.0,KAIA,KAIA,kaia,0x0000000000000000000000000000000000000000
95,34104,Morpho,MORPHO,morpho,202,2024-11-21T10:30:00.000Z,"[defi, ethereum-ecosystem, coinbase-ventures-p...",1.000000e+09,3.702723e+08,1.000000e+09,...,4.811682e+08,0.0158,1.299498e+09,NaN,2025-12-05T20:14:00.000Z,1027.0,Ethereum,ETH,ethereum,0x58D97B57BB95320F9a05dC918Aef65434969c2B2
96,6719,The Graph,GRT,the-graph,596,2020-12-17T00:00:00.000Z,"[ai-big-data, enterprise-solutions, defi, ethe...",NaN,1.061978e+10,1.141980e+10,...,4.798266e+08,0.0158,5.159732e+08,NaN,2025-12-05T20:12:00.000Z,1027.0,Ethereum,ETH,ethereum,0xc944e90c64b2c07662a292be6244bdf05cda44a7
97,3871,AB,AB,newton,69,2019-04-17T00:00:00.000Z,"[mineable, marketplace, enterprise-solutions, ...",9.882366e+10,8.998888e+10,9.882366e+10,...,4.773571e+08,0.0157,5.242223e+08,NaN,2025-12-05T20:14:00.000Z,1839.0,BNB Smart Chain (BEP20),BNB,bnb,0x95034f653d5d161890836ad2b6b8cc49d14e029a
98,29814,ether.fi,ETHFI,ether-fi-ethfi,308,2024-03-13T06:06:39.000Z,"[defi, staking, ethereum-ecosystem, binance-la...",1.000000e+09,6.084617e+08,1.000000e+09,...,4.699839e+08,0.0154,7.724133e+08,NaN,2025-12-05T20:14:00.000Z,1027.0,Ethereum,ETH,ethereum,0xFe0c30065B384F05761f15d0CC899D4F9F9Cc0eB

In [19]:
columns_to_drop  = ["num_market_pairs", "quote_USD_tvl", "infinite_supply", "minted_market_cap",
                    "platform", "cmc_rank", "self_reported_circulating_supply", "self_reported_market_cap",
                    "tvl_ratio", "tags", "slug", "id"]

df = df.drop(columns_to_drop, axis = 1)

df

,name,symbol,date_added,max_supply,circulating_supply,total_supply,last_updated,quote_USD_price,quote_USD_volume_24h,quote_USD_volume_change_24h,...,quote_USD_percent_change_90d,quote_USD_market_cap,quote_USD_market_cap_dominance,quote_USD_fully_diluted_market_cap,quote_USD_last_updated,platform_id,platform_name,platform_symbol,platform_slug,platform_token_address
0,Bitcoin,BTC,2010-07-13T00:00:00.000Z,2.100000e+07,1.995781e+07,1.995781e+07,2025-12-05T20:14:00.000Z,89592.061735,6.296189e+10,-7.4880,...,-18.613790,1.788061e+12,58.7621,1.881433e+12,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
1,Ethereum,ETH,2015-08-07T00:00:00.000Z,NaN,1.206954e+08,1.206954e+08,2025-12-05T20:14:00.000Z,3037.977807,2.800235e+10,-7.5563,...,-28.721896,3.666700e+11,12.0501,3.666700e+11,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
2,Tether USDt,USDT,2015-02-25T00:00:00.000Z,NaN,1.855162e+11,1.878597e+11,2025-12-05T20:11:00.000Z,1.000265,9.819052e+10,-7.2585,...,0.021249,1.855653e+11,6.0896,1.879095e+11,2025-12-05T20:11:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,XRP,XRP,2013-08-04T00:00:00.000Z,1.000000e+11,6.033164e+10,9.998575e+10,2025-12-05T20:14:00.000Z,2.032363,3.385291e+09,-4.3522,...,-27.353455,1.226158e+11,4.0296,2.032363e+11,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
4,BNB,BNB,2017-07-25T00:00:00.000Z,1.377360e+08,1.377360e+08,1.377360e+08,2025-12-05T20:14:00.000Z,881.962486,1.992338e+09,-8.1091,...,2.862301,1.214780e+11,3.9922,1.214780e+11,2025-12-05T20:14:00.000Z,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Kaia,KAIA,2024-10-29T05:17:50.000Z,NaN,6.185546e+09,6.185546e+09,2025-12-05T20:14:00.000Z,0.077985,1.465276e+07,50.8716,...,-46.110382,4.823800e+08,0.0159,4.823800e+08,2025-12-05T20:14:00.000Z,32880.0,KAIA,KAIA,kaia,0x0000000000000000000000000000000000000000
95,Morpho,MORPHO,2024-11-21T10:30:00.000Z,1.000000e+09,3.702723e+08,1.000000e+09,2025-12-05T20:14:00.000Z,1.299498,2.292257e+07,-33.8943,...,-33.880491,4.811682e+08,0.0158,1.299498e+09,2025-12-05T20:14:00.000Z,1027.0,Ethereum,ETH,ethereum,0x58D97B57BB95320F9a05dC918Aef65434969c2B2
96,The Graph,GRT,2020-12-17T00:00:00.000Z,NaN,1.061978e+10,1.141980e+10,2025-12-05T20:12:00.000Z,0.045182,2.686152e+07,-0.6507,...,-48.116697,4.798266e+08,0.0158,5.159732e+08,2025-12-05T20:12:00.000Z,1027.0,Ethereum,ETH,ethereum,0xc944e90c64b2c07662a292be6244bdf05cda44a7
97,AB,AB,2019-04-17T00:00:00.000Z,9.882366e+10,8.998888e+10,9.882366e+10,2025-12-05T20:14:00.000Z,0.005305,1.150976e+07,-26.8794,...,-38.342334,4.773571e+08,0.0157,5.242223e+08,2025-12-05T20:14:00.000Z,1839.0,BNB Smart Chain (BEP20),BNB,bnb,0x95034f653d5d161890836ad2b6b8cc49d14e029a
98,ether.fi,ETHFI,2024-03-13T06:06:39.000Z,1.000000e+09,6.084617e+08,1.000000e+09,2025-12-05T20:14:00.000Z,0.772413,3.586642e+07,-18.0207,...,-32.852015,4.699839e+08,0.0154,7.724133e+08,2025-12-05T20:14:00.000Z,1027.0,Ethereum,ETH,ethereum,0xFe0c30065B384F05761f15d0CC899D4F9F9Cc0eB